spring.application.name=PriceTracker
# --- ????????? ??????????? ? PostgreSQL ---
# ????? ???? (localhost, ???? 5432, ??? ???? pricetracker)
spring.datasource.url=jdbc:postgresql://localhost:5432/pricetracker
# ????? ? ??????, ??????? ?? ??????? ? ???? 1
spring.datasource.username=
spring.datasource.password=
# --- ????????? Hibernate (ORM) ---
# ????????????? ????????? ??????? ?? ?????? ????? Java-??????? (@Entity)
spring.jpa.hibernate.ddl-auto=update
# ?????????? SQL-??????? ? ??????? (?????? ??? ???????)
spring.jpa.show-sql=true
# ????????????? SQL ???????
spring.jpa.properties.hibernate.format_sql=true
# ????????? ??????? (Spring ?????? ??? ????????, ?? ???????? ???????)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
